// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvNaJDApcA23fw06NbIQUq6qPc7WUk3Qc',
    appId: '1:701401180006:web:ba4e0c7691a7d2c0bc8aa7',
    messagingSenderId: '701401180006',
    projectId: 'staff-tracker-62e82',
    authDomain: 'staff-tracker-62e82.firebaseapp.com',
    storageBucket: 'staff-tracker-62e82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuq595vzkbFZw0LYipvG1-aQQ9QuqpGsM',
    appId: '1:701401180006:android:cf4a2615d44c9045bc8aa7',
    messagingSenderId: '701401180006',
    projectId: 'staff-tracker-62e82',
    storageBucket: 'staff-tracker-62e82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAwdHv3pMEvsjTpaLleOmXVRyEq5-pZrw',
    appId: '1:701401180006:ios:4103ec29d0b21518bc8aa7',
    messagingSenderId: '701401180006',
    projectId: 'staff-tracker-62e82',
    storageBucket: 'staff-tracker-62e82.firebasestorage.app',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAwdHv3pMEvsjTpaLleOmXVRyEq5-pZrw',
    appId: '1:701401180006:ios:64ff145bfa71db28bc8aa7',
    messagingSenderId: '701401180006',
    projectId: 'staff-tracker-62e82',
    storageBucket: 'staff-tracker-62e82.firebasestorage.app',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvNaJDApcA23fw06NbIQUq6qPc7WUk3Qc',
    appId: '1:701401180006:web:f557a6a41173801bbc8aa7',
    messagingSenderId: '701401180006',
    projectId: 'staff-tracker-62e82',
    authDomain: 'staff-tracker-62e82.firebaseapp.com',
    storageBucket: 'staff-tracker-62e82.firebasestorage.app',
  );
}
